# Generated by Django 5.0.7 on 2024-10-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boke", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
