# Generated by Django 5.0.7 on 2024-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("hobbies", models.CharField(blank=True, max_length=300)),
                ("introduction", models.TextField(blank=True)),
            ],
        ),
    ]
