# Generated by Django 5.0.7 on 2024-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_password_alter_user_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="introduction",
            new_name="interests",
        ),
    ]
