# Generated by Django 5.0.7 on 2024-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_introduction_user_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
